@base_url_user = http://localhost:3000/users
@base_url_auth = http://localhost:3000/auth
@access_token = Bearer {{user_login.response.body.accessToken}}

# @name user_create
POST {{base_url_user}}/users
Content-Type: application/json

{
	"name": "Matheus",
	"email": "matheus2@mail.com",
	"password": "Password@123"
}
###

# @name user_list
GET {{base_url_user}}
###

# @name user_findOne
GET {{base_url_user}}/2
###

# @name user_update
PUT {{base_url_user}}/1
Content-Type: application/json

{
	"name": "Matheus"
}
###

# @name user_update_partial
PATCH {{base_url_user}}/1
Content-Type: application/json

{
	"name": "Matheus de Gondra"
}
###

# @name user_delete
DELETE {{base_url_user}}/1
###

# @name user_login
POST {{base_url_auth}}/login
Content-Type: application/json

{
	"email": "matheus2@mail.com",
	"password": "Password@123"
}
###

# @name user_me
GET {{base_url_auth}}/me
Authorization: {{access_token}}